document.write ('<section class="otp-full-width td-fullwidth-white">\n');
document.write ('    <div class="td-in-page-banner">\n');
document.write ('        <div class="td-container">\n');
document.write ('            <a href="#/">\n');
document.write ('                <div class="td-row">\n');
document.write ('                    <div class="td-col-xs-12">\n');
document.write ('                        <picture>\n');
document.write ('                            <source srcset="https://oasc17.247realmedia.com/RealMedia/ads/Creatives/TDBank/TD-app_and_Mobile_Deposit_TDCT_EN_Oct2017@TD-app_and_Mobile_Deposit_EW_LI_AAM_EN_Nov2017/\n');
document.write ('2724-0717_TDMobileDeposit_TDCT_WB_In-Page_DESKTOP_1170x260_E.jpg" media="(min-width: 1200px)">\n');
document.write ('                            <source srcset="https://oasc17.247realmedia.com/RealMedia/ads/Creatives/TDBank/TD-app_and_Mobile_Deposit_TDCT_EN_Oct2017@TD-app_and_Mobile_Deposit_EW_LI_AAM_EN_Nov2017/\n');
document.write ('2724-0717_TDMobileDeposit_TDCT_WB_In-Page_DESKTOP_1170x260_E.jpg" media="(min-width: 1024px)">\n');
document.write ('                            <source srcset="https://oasc17.247realmedia.com/RealMedia/ads/Creatives/TDBank/TD-app_and_Mobile_Deposit_TDCT_EN_Oct2017@TD-app_and_Mobile_Deposit_EW_LI_AAM_EN_Nov2017/\n');
document.write ('2724-0717_TDMobileDeposit_TDCT_WB_In-Page_TABLET-LANDSCAPE_1024x260_E.jpg" media="(min-width: 768px)">\n');
document.write ('                            <source srcset="https://oasc17.247realmedia.com/RealMedia/ads/Creatives/TDBank/TD-app_and_Mobile_Deposit_TDCT_EN_Oct2017@TD-app_and_Mobile_Deposit_EW_LI_AAM_EN_Nov2017/2724-0717_TDMobileDeposit_TDCT_WB_In-Page_MOBILE_640x520_E.jpg" media="(max-width: 768px)">\n');
document.write ('                            <!-- Following is fallback for IE. Serve the LG image because we know it');
document.write ("'");
document.write ('s a desktop -->\n');
document.write ('                            <img class="img-responsive td-big-promos" src="https://oasc17.247realmedia.com/RealMedia/ads/Creatives/TDBank/TD-app_and_Mobile_Deposit_TDCT_EN_Oct2017@TD-app_and_Mobile_Deposit_EW_LI_AAM_EN_Nov2017/\n');
document.write ('2724-0717_TDMobileDeposit_TDCT_WB_In-Page_DESKTOP_1170x260_E.jpg" alt="Deposit cheques on the go. Safely and securely deposit cheques from almost anywhere using TD Mobile Deposit. Learn more">\n');
document.write ('                        </picture>\n');
document.write ('                    </div>\n');
document.write ('                    <div class="td-col-sm-8 td-col-sm-offset-4 td-col-md-7 td-col-md-offset-5 td-banner-content">\n');
document.write ('                        <h2>Deposit cheques on the go</h2>\n');
document.write ('                        <p class="td-copy-emphasized">\n');
document.write ('                            <span class="td-rwd-line">Safely and securely deposit cheques from almost</span>\n');
document.write ('                            <span class="td-rwd-line" >anywhere using TD Mobile Deposit</span>\n');
document.write ('                        </p>\n');
document.write ('                        <div class="td-cta">\n');
document.write ('                            <button class="td-button td-button-clear-green td-button-block ng-binding" onclick="window.open(');
document.write ("'");
document.write ('https://ads.td.com/RealMedia/ads/click_lx.ads/www.td.com/tdct/en/login/L24/406974789/Middle/TDBank/TD-app_and_Mobile_Deposit_TDCT_EN_Oct2017@TD-app_and_Mobile_Deposit_EW_LI_AAM_EN_Nov2017/TD-app_and_Mobile_Deposit_EW_LI_vTDMobDep2_AAM_EN_c000-01-9540.html/3279586f34467644774f414144653768');
document.write ("'");
document.write (', ');
document.write ("'");
document.write ('_blank');
document.write ("'");
document.write (');">Learn More</button>\n');
document.write ('                        </div>\n');
document.write ('                    </div>\n');
document.write ('                </div>\n');
document.write ('            </a>\n');
document.write ('        </div>\n');
document.write ('    </div>\n');
document.write ('</section>');
